name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    name: Build, Analyze, and Run Tests
    runs-on: ubuntu-latest

    steps:
      # 1. Clone the repository
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for better relevancy of analysis

      # 2. Install dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential

      # 3. Configure, Build, and Run Tests
      - name: Configure, Build, and Test
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build .
          ctest --output-on-failure

      # 4. Run SonarQube Analysis
      - name: SonarQube Analysis
        uses: sonarsource/sonarqube-scan-action@v3
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      # 5. Optionally enforce Quality Gate
      # Uncomment this section if you want the build to fail if the Quality Gate is red
      # - name: SonarQube Quality Gate Check
      #   uses: sonarsource/sonarqube-quality-gate-action@master
      #   timeout-minutes: 5
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
